### PR TITLE
Support sending messages directly to DLQ

### PR DESCRIPTION
**Pull request by SeriousBug**
Adds support for sending SQS messages directly to the DLQ, bypassing the regular queue.

This can be useful in cases where a lambda handler receives a message known to be bad, and we want to record that we got this message for manual review later. Instead of sending said message to a different queue, we can put it in the DLQ directly.

### CODE REVIEW

**Review by mckalexee — COMMENTED** [review]
Thanks for contributing! I'd like to kick off a discussion about this to make sure it's a pattern we want to adopt for this library.

Conceptually I view DLQ messages being messages that have some unexpected exception when trying to handle them. 

Specifically, when trying to process a message something truly unexpected happened that isn't a part of the normal control flow for a handler.

Sending a message directly to the DLQ as an indented target means that some messages in the DLQ were supposed to be there.

IMO the pattern of rejecting the message if we can't process it is better than sending it straight to the DLQ, but I'm curious to hear your perspective on this!

**Comment by SeriousBug** [comment]
Thanks for your answer @mckalexee ! Let me describe the use case, maybe you can comment if this pattern makes sense:

I have a lambda handler that's used as a webhook. This webhook receives requests from a service. One of the requirements of this service is that if my webhook handlers start returning non-200 responses, they will turn off my service integration. To avoid that, I want to always accept the webhook requests and immediately put them in a queue.

My webhook handler makes some checks for the incoming request. These checks would only fail if the service that sends the requests breaks backwards compatiblity or sends something unexpected. My thought here is that if the checks fail, I can send the message directly into the DLQ. Because if I ignore the failing checks and queue the request, the queue handler will repeatedly fail until the message hits the DLQ anyway. This PR allows me to skip queuing a message that I know will fail, and immediately send it to the DLQ to be reviewed manually later.

**Comment by kensenjohn** [comment]
@mckalexee
Please see Kaan's message above.

> Conceptually I view DLQ messages being messages that have some unexpected exception when trying to handle them.
> Specifically, when trying to process a message something truly unexpected happened that isn't a part of the normal control flow for a handler.

Alex, the use case we need this is exactly as you have described above.

The data for the queue handler is coming from a 3rd party. We have no control over this data. 
We expect the event object to have a specific specific shape and properties.

Since we do not have control over what the 3rd part sends us, they could change the object. When this happens we do not want to return back an error. We want to acknowledge the request with a 200. Then send the data to DLQ so that we can handle it individually.

**Review by mckalexee — APPROVED** [review]
@kensenjohn @SeriousBug  Sorry for the delayed reply here.

I'm happy to approve this and merge this! Any maintainer of Faceteer can also approve and merge any PR as well so that I'm not a blocker. (@s-fletcher @loganhuskins @bill-kerr @AnYoung627)

Just to give some advice, I wouldn't generally recommend this pattern though. Reserving the DLQ for unhandled failures and letting AWS put things on the DLQ keeps failure modes separated in a cleaner fashion. 

If you get a message on the DLQ, it means there was a failure that the event handler could not recover, and you need to fix your code.

The use case your mentioning is different, since it's a known failure mode. 

You're validating some payload from a third party, expecting that there might be invalid payloads. Putting these failures into the same queue can make it more difficult to figure out what's going wrong when something is in the DLQ, and it makes it harder to set up different alerts for the different failures.

Here's what I'd recommend, feel free to take it or leave it!

Since you already know the shape of the message is wrong before you put it on the queue, you could simply not put it on the queue.

I'd recommend taking the malformed payloads from the third party and putting them on another queue that's designed to handle malformed messages, or you could dump the raw message into S3 and fire an alert, or however you want to handle and respond to these payloads. You can still return a 200 in the http response.

S3 is a nice option since the messages will be there permanently, where SQS will remove them after X days.

If you still need this feature added, I've approved it, and myself or any maintainer can merge it and release it!

**Pull request closed without merging**
